db.tipo=h2
db.carpeta=./data/
db.nombre=BBDD_Empresa
db.user=root
db.password=

# Rutas de ficheros
csv.path.customers=./data/customers-1000.csv
csv.path.Bills=./data/facturas.csv
sql.customerTable=./sql/TablaClientes.sql
sql.BillTable=./sql/TablaFacturas.sql
temp.path=./temp/pendientes